const TipoLeito = Object.freeze({
  UTI_1 = 'UTI1',
  UTI_2 = 'UTI2',
  UTI_3 = 'UTI3',
  UTI_4 = 'UTI4',
  UTI_5 = 'UTI5',
  UTI_6 = 'UTI6',

  UTI_PED = 'UTIPED',
  UTI_NEO = 'UTINEO',

  UTQ = 'UNIDADE TRATAMENTO QUEIMADOS',
  CTQ = 'CENTRAL TRATAMENTO QUEIMADOS',

  UB = 'UNIDADE MASCULINA',
  UD = 'UNIDADE FEMININA',
  UA = 'UNIDADE PSIQUIATRICA',
  UE = 'MOLESTIAS INFECCIOSAS',

  UF = 'UNIDADE OPERATORIA',
  PED = 'PEDIATRIA',
  AC = 'ALOJAMENTO CONJUNTO',
  PPP = 'PARTO_NORMAL',

  PS1 = 'PRONTO SOCORRO FEMININO',
  PS2 = 'PRONTO SOCORRO CIRURGICO',
  PS3 = 'PRONTO SOCORRO MASCULINO',
  PS4 = 'PRONTO SOCORRO 4',
  
  PSM = 'PRONTO SOCORRO MEDICO',
  PSA = 'PRONTO SOCORRO RESPIRATORIO',

  EMER = 'EMERGENCIA PS',
  PSI = 'PRONTO SOCORRO ESTABILIZACAO',
})